<a href="https://colab.research.google.com/github/udomdev/ReduxSimpleStarter/blob/master/lab10_problem1_convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib.pyplot as plt
import numpy as np

plt.style.use('default')

input_your_code = None

In [0]:
'''Create a convolution2d method.
You can use a naive algorithm by sliding a kernel on top of the image
Element-wise multiply kernel with the image area under the kernel,
sum all the values and then store it into each location of a new image output.
'''
def convolution2d(image, kernel, bias=0):
  m, n = kernel.shape
  # Check if a kernel has square shape
  if (m == n):
    y, x = image.shape
    '''Dimension for the output
    output_dimension = (input_dimension + 2*padding_size - kernel_size)/stride + 1
    In this case padding is zero, stride is one, there fore we have the output shape
    as we seen below.
    '''
    padding = 0
    stride = 1
    input_your_code
    
    feature_map = np.zeros((width, height)).astype('int8')
    
    '''Moving kernel from top left of the image and 
    multiply element-wise between kernel and image area under the kernel,
    then sum all values (This is actually dot product).
    '''
    input_your_code

    return feature_map
 


def display(image):
  print(image)
  plt.grid(c='grey')
  plt.xticks(np.arange(0, image.shape[0]+1, dtype=np.int))
  plt.yticks(np.arange(0, image.shape[1]+1, dtype=np.int))
  plt.imshow(
      image,
      cmap=plt.cm.gray,
      extent=[0, image.shape[0], 0, image.shape[1]]
  )
  plt.show()

# Vertical Edge Detection



In [0]:
'''Create numpy array as image1 and display it.
[[10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]]
 '''

image1 = input_your_code
# display(image1)

In [0]:
'''Create vertical_edge_kernel and display it:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]
'''

vertical_edge_kernel = input_your_code
# display(vertical_edge_kernel)

In [0]:
# Call your convolution2d() and display the result.
input_your_code

In [0]:
'''Create a numpy array and display it:
[[ 0  0  0 10 10 10]
 [ 0  0  0 10 10 10]
 [ 0  0  0 10 10 10]
 [ 0  0  0 10 10 10]
 [ 0  0  0 10 10 10]
 [ 0  0  0 10 10 10]]
'''
image2 = input_your_code

# display(image2)

In [0]:
# Call your convolution2d() and display the result.
input_your_code

# Horizontal Edge Detection

In [0]:
'''Create horizontal_edge_kernel and display it:
[[ 1  1  1]
 [ 0  0  0]
 [-1 -1 -1]]

'''
horizontal_edge_kernel = input_your_code

# display(horizontal_edge_kernel)

In [0]:
'''Create an numpy array and display it:
[[10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [10 10 10  0  0  0]
 [ 0  0  0 10 10 10]
 [ 0  0  0 10 10 10]
 [ 0  0  0 10 10 10]]
'''
image3 = input_your_code

# display(image3)

In [0]:
'''Value 0 means there is no edge detected.
Value 30 means 3 bright pixels on top, 3 dark pixels on the bottom.
Value -30 means 3 dark pixels on top, 3 bright pixels on the bottom.
Value 10 is similar to 30 some part of the edge is not bright pixel on top and dark pixel on the bottom.
Value -10 is similar to -30 some part of the edge is not dark pixel on top and bright pixel on the bottom.

'''
# Call your convolution2d(), store it as image4, and display the result.
image4 = input_your_code
# display(image4)

In [0]:
# Apply vertical edge kernel on the previous feature maps to see the result.
# display(vertical_edge_kernel)
# display(convolution2d(image4, vertical_edge_kernel))